### ISSUE TITLE
Test with Node 7x

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/lightbright#15]
```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Async hooks called unexpectedly: 5
    at process.once (/mnt/ddisk/dev/lightbright/test/test-filter-reactivation.js:37:10)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
 - failed
failed - 1 tests failed
```

**Comment by helio-frota** [comment]
Related to: https://github.com/bucharest-gold/entente/issues/107

**Comment by helio-frota** [comment]
great!
